version: 0.0
os: linux
files:
  - source: /
    destination: /opt/application
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
#  ValidateService:
#    - location: scripts/validate_service.sh
#      timeout: 300
